# Generated by Django 5.0.6 on 2024-06-29 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_comment_options_alter_rating_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('product', 'user')},
        ),
    ]
