# Generated by Django 5.0.6 on 2024-06-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-score']},
        ),
    ]
